### ISSUE TITLE
Trying to install on Mac OS X  

### ISSUE THREAD

**Issue by prajwalkirankumar** [wcohen/libpfm4#1]
install  /Users/prajwalkirankumar/Documents/JXPerf-master/build/thirdparty/lib
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make[2]: * [install] Error 64
make[1]: * [install] Error 2
make: * [thirdparty] Error 2

Finding this error on running make.
Any modifications needed for the makefile?

**Comment by wcohen** [comment]
You should ask this question on the official libpfm support page, https://sourceforge.net/p/perfmon2/support-requests/ . This is my personal fork of the repository.
