### ISSUE TITLE
Clarify that this is a fork

### ISSUE THREAD

**Issue by travisdowns** [wcohen/libpfm4#5]
FWIW, this is the top hit on Google for `libpfm4` appearing before the actual project repo/pages. It might be useful to indicate that this is a fork/mirror (which is it?) in the project description in GitHub, to avoid confusion and prevent users from opening issues, etc.

**Comment by wcohen** [comment]
Put the following in the "About" on https://github.com/wcohen/libpfm4 :

This is a mirror of the official libpfm4 git repository, https://sourceforge.net/p/perfmon2/libpfm4/ci/master/tree/ with some local branch for developing patches.

**Comment by travisdowns** [comment]
Awesome, thanks!
